# Generated by Django 4.2.11 on 2026-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_conversations',
            field=models.BooleanField(default=False, help_text='User consented to conversation storage and processing.'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_impact_survey',
            field=models.BooleanField(default=False, help_text='User consented to optional impact survey.'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_usage_tracking',
            field=models.BooleanField(default=False, help_text='User consented to anonymised usage data collection.'),
        ),
    ]
