# Generated by Django 4.2.11 on 2026-04-22 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_consent_conversations_user_consent_given_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('baseline', 'Baseline (signup)'), ('followup', 'Follow-up (4 weeks)')], max_length=10)),
                ('handle_difficult_moments', models.PositiveSmallIntegerField(help_text='In the past week, I felt able to handle difficult moments in my day.')),
                ('notice_stress_building', models.PositiveSmallIntegerField(help_text='I notice when my stress or emotions are building up before they become overwhelming.')),
                ('have_something_to_try', models.PositiveSmallIntegerField(help_text='When I feel stuck or overwhelmed, I have something I can try that helps.')),
                ('get_through_daily_tasks', models.PositiveSmallIntegerField(help_text='I have been able to get through my daily tasks and responsibilities.')),
                ('feel_more_grounded', models.PositiveSmallIntegerField(blank=True, help_text='Overall, I feel more steady and grounded in my daily life than I did a month ago.', null=True)),
                ('age_range', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_25', '18-25'), ('26_35', '26-35'), ('36_50', '36-50'), ('51_65', '51-65'), ('over_65', 'Over 65')], max_length=10)),
                ('situation', models.JSONField(blank=True, default=list, help_text='Multiple select: working_ft, working_pt, studying_ft, studying_pt, parent')),
                ('country', models.CharField(blank=True, choices=[('fi', 'Finland'), ('ee', 'Estonia'), ('other', 'Other')], max_length=10)),
                ('what_brought_you', models.TextField(blank=True, help_text='What brought you to Companion OS? (baseline)')),
                ('what_changed', models.TextField(blank=True, help_text='Is there anything that has changed in your daily life? (follow-up)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
