# Generated by Django 4.2.11 on 2026-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_impactsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactsurvey',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
