# Generated by Django 4.2.11 on 2026-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_usageevent_mode_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('conversation_created', 'Conversation created'), ('conversation_deleted', 'Conversation deleted'), ('mode_used', 'Mode used')], max_length=30),
        ),
    ]
