# Generated by Django 4.2.11 on 2026-04-20 19:36

import apps.chat.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=apps.chat.fields.EncryptedTextField(),
        ),
    ]
